### ISSUE TITLE
wrong memory calculation?

### ISSUE THREAD

**Issue by the2nd** [pixelb/ps_mem#15]
Our backup server currently runs and rdiff-backup process which is checking the destination dir and uses a lot of memory. but ps_mem.py does not show it:

root@bserver3:~# ps_mem.py 
 Private  +   Shared  =  RAM used       Program

180.0 KiB +  36.5 KiB = 216.5 KiB       acpid
192.0 KiB +  28.5 KiB = 220.5 KiB       atd
232.0 KiB +  34.5 KiB = 266.5 KiB       rpc.idmapd
200.0 KiB +  73.0 KiB = 273.0 KiB       pv (2)
152.0 KiB + 144.5 KiB = 296.5 KiB       sh (3)
280.0 KiB +  52.0 KiB = 332.0 KiB       upstart-file-bridge
260.0 KiB +  78.5 KiB = 338.5 KiB       upstart-udev-bridge
288.0 KiB +  66.0 KiB = 354.0 KiB       cron
360.0 KiB +  53.5 KiB = 413.5 KiB       upstart-socket-bridge
324.0 KiB +  99.5 KiB = 423.5 KiB       rpcbind
352.0 KiB + 142.5 KiB = 494.5 KiB       systemd-logind
300.0 KiB + 206.5 KiB = 506.5 KiB       pickup
336.0 KiB + 208.5 KiB = 544.5 KiB       qmgr
352.0 KiB + 201.5 KiB = 553.5 KiB       master
576.0 KiB +  56.5 KiB = 632.5 KiB       dbus-daemon
544.0 KiB + 110.0 KiB = 654.0 KiB       rpc.statd
764.0 KiB +  75.5 KiB = 839.5 KiB       systemd-udevd
836.0 KiB + 114.0 KiB = 950.0 KiB       ntpd
956.0 KiB + 166.5 KiB =   1.1 MiB       bacula-fd
  1.1 MiB + 188.5 KiB =   1.3 MiB       rbackup
  1.1 MiB + 298.0 KiB =   1.4 MiB       getty (7)
  1.5 MiB + 142.5 KiB =   1.6 MiB       init
  1.3 MiB + 359.5 KiB =   1.6 MiB       ssh
  1.4 MiB + 332.5 KiB =   1.7 MiB       screen (2)
  1.9 MiB +  69.0 KiB =   1.9 MiB       rsyslogd
  1.8 MiB + 322.5 KiB =   2.1 MiB       bacula-dir
  2.0 MiB +   1.1 MiB =   3.1 MiB       sshd (2)
  2.5 MiB + 704.0 KiB =   3.2 MiB       iscsid (2)
  3.5 MiB +  78.0 KiB =   3.5 MiB       snmpd
  2.9 MiB + 791.5 KiB =   3.7 MiB       multipathd
  3.5 MiB + 779.0 KiB =   4.3 MiB       bash (3)
 12.9 MiB +   3.3 MiB =  16.2 MiB       postgres (6)
 40.1 MiB +   1.0 MiB =  41.1 MiB       rdiff-backup
---------------------------------
                         95.9 MiB
=================================

root@bserver3:~# free -m
             total       used       free     shared    buffers     cached
Mem:         64433      64087        346         12          6        690
-/+ buffers/cache:      63389       1043
Swap:         2047          0       2047

root@bserver3:~# ps -eo rss,cmd --sort=rss | tail -n 3 | cut -b -50
 5252 /sbin/multipathd
16092 /usr/lib/postgresql/9.3/bin/postgres -D /var
44264 /usr/bin/python /usr/bin/rdiff-backup --term

**Comment by pixelb** [comment]
Are you talking about the discrepancy between 41.1MiB and 43.2MiB reported by ps ?
That may be due to running ps a little later?

**Comment by the2nd** [comment]
sorry i missed the detail that rss in in kilo bytes :)

but i'm still confused about the output of free -m:
 -/+ buffers/cache: 63389 1043

there is 63G of 65G memory used and i'm sure its used by rdiff-backup. but it's not show anywhere. or do i miss something?

**Comment by pixelb** [comment]
Well ps_mem is reporting what the kernel is telling us. Perhaps you're hitting the kernel reporting issue wrt AnonHugePages (https://lkml.org/lkml/2014/10/9/109)? You might sport that in /proc/$(pidof rdiff-backup)/smaps
