### ISSUE TITLE
[Feature Request]: Provide options to sort(reverse) and limit number of process

### ISSUE THREAD

**Issue by ChillarAnand** [pixelb/ps_mem#26]

**Comment by pixelb** [comment]
yes the header and total lines make this awkward with standard `tac` and `tail` tools.
I wonder would an option to suppress those lines be a more general solution?

**Comment by ChillarAnand** [comment]
Can use `-w 3` option with above function?

**Comment by pixelb** [comment]
No, but -w is an option that also doesn't need to be internal and probably shouldn't have been added.
You can achieve the same thing with:

    $ watch -n3 'sudo ps_mem | tail -n+2 | head -n-3 | tail -n10 | tac'

**Comment by ChillarAnand** [comment]
Excellent. Thank you :-)
