### ISSUE TITLE
3.13 release?

### ISSUE THREAD

**Issue by gnidorah** [pixelb/ps_mem#51]
@pixelb 
Hi! I'm a package maintainer of your program in NixOS distro
Was this a new release? https://github.com/pixelb/ps_mem/commit/9f54e1aa3a87ec176ce8b71f02673e0d8293b344
If so, could you please make a new release from it here? https://github.com/pixelb/ps_mem/releases

**Comment by pixelb** [comment]
done. thanks

**Comment by gnidorah** [comment]
@pixelb Thank you!
