### ISSUE TITLE
does not work on ubuntu 20.04 with pip3 install --user

### ISSUE THREAD

**Issue by laoshaw** [pixelb/ps_mem#61]
I can install it and it is under $HOME/.local/bin/ps_mem: 

```
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from ps_mem import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

ModuleNotFoundError: No module named 'ps_mem'

it used to fine under ubuntu 18.04 with the same command.

if I do `sudo pip3 install ps_mem` it works well though.

**Comment by NHellFire** [comment]
Works for me:
```bash
nathan:~$ which -a ps_mem
/home/nathan/.local/bin/ps_mem
nathan:~$ ps_mem -p $$
 Private  +   Shared  =  RAM used	Program

  1.8 MiB +   2.7 MiB =   4.5 MiB	bash
---------------------------------
                          4.5 MiB
=================================
```

Are you trying to run it with sudo?
That won't work, as it won't use the packages installed under your account.

**Comment by laoshaw** [comment]
now it works 'sudo /home/xyz/.local/bin/ps_mem', not sure what changed.

**Comment by parkerlreed** [comment]
Your user python env isnt setup to look for modules. sudo is working because it then looks for the modules in the root installled path which exists.
