### ISSUE TITLE
Hugepage Memory not computed correctly 

### ISSUE THREAD

**Issue by lari-arjun** [pixelb/ps_mem#64]
I have run ps_mem.py on a process and it has negative value in output as that process is using hugepages

 python ps_mem.py -d -p 16299
 Private  +   Shared  =  RAM used    Program[pid]

  2.0 GiB + -2095209.5 KiB =   4.3 MiB    ora_smon_stgtes [16299]
---------------------------------
                          4.3 MiB
=================================

 cat /proc/16299/smaps_rollup
00400000-ffffffffff601000 ---p 00000000 00:00 0                          [rollup]
Rss:               49072 kB
Pss:                4446 kB
Shared_Clean:      46568 kB
Shared_Dirty:          0 kB
Private_Clean:       196 kB
Private_Dirty:      2308 kB
Referenced:        49072 kB
Anonymous:          2308 kB
LazyFree:              0 kB
AnonHugePages:         0 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:    90112 kB
Private_Hugetlb: 2097152 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB

##kernel Version 
4.14.35-1902.301.1.el7uek.x86_64

Huge Page size is 2048Kb but os.sysconf(SC_PAGE_SIZE) is picking 4Kb page size.

grep -i huge /proc/meminfo
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:   23764
HugePages_Free:    23764
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB

######
As per script logic, the automation is not considering hugetlb values and due to that this value is not correctly computed.
Correct me if i am wrong in computing memory value

**Comment by pixelb** [comment]
Fixed in commit f26d3f4
