### ISSUE TITLE
Add an option to show the sum of all used memory, including swap

### ISSUE THREAD

**Issue by MurzNN** [pixelb/ps_mem#79]
Will be good to add an option to show the sum of all used memory, including swap, cuz some applications really use a lot of swap memory in time, but now it's not easy to catch them.

**Comment by pixelb** [comment]
We already show the total swap in the output from `sudo ps_mem -S`.
If you want an exact total of core + swap used you could use:
`echo $(($(sudo ps_mem --total) + $(sudo ps_mem -S --total)))`

**Comment by MurzNN** [comment]
I want to see the sum of "ram + swap" per program (and sort by this sum), not the total usage of swap.
