### ISSUE TITLE
Nuitka build

### ISSUE THREAD

**Issue by megastallman** [pixelb/ps_mem#81]
Can we please add a native Linux x86_64 build with Nuitka compiler? It would be nice for those people who don't want to install PIP.
I'm building Ps_mem with the following command: `nuitka3 --follow-imports /tmp/rrr/venv/bin/ps_mem` from within a temporary Virtualenv.

**Comment by pixelb** [comment]
I'm not sure how general it is to be providing binaries.
I'd be very wary for running binaries directly from github at least.
python is ubiquitous enough, and ps_mem is a single script, so it should be trivial for almost everyone to install
